/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.LottoCalendar;
import Controller.LottoMatriz;
import Model.LottoTicket;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Acekuroko
 */
public class LottoPickerUI extends javax.swing.JFrame {

        LottoCalendar lottoCal;
    /**
     * Creates new form LottoPickerUI
     */
    public LottoPickerUI() {
        super("Lotto Picker");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGenerate = new javax.swing.JButton();
        jDCFechaSorteo = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jPLottoMatriz = new javax.swing.JPanel();
        jLLottoMatriz = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jBGenerate.setText("Generar");
        jBGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGenerateActionPerformed(evt);
            }
        });

        jLabel1.setLabelFor(jDCFechaSorteo);
        jLabel1.setText("Fecha del siguiente sorteo:");

        jPLottoMatriz.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.gray));

        javax.swing.GroupLayout jPLottoMatrizLayout = new javax.swing.GroupLayout(jPLottoMatriz);
        jPLottoMatriz.setLayout(jPLottoMatrizLayout);
        jPLottoMatrizLayout.setHorizontalGroup(
            jPLottoMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLLottoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPLottoMatrizLayout.setVerticalGroup(
            jPLottoMatrizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLLottoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPLottoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jDCFechaSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jBGenerate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDCFechaSorteo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPLottoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGenerate))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGenerateActionPerformed
        Date date = jDCFechaSorteo.getDate();
        lottoCal = new LottoCalendar(date, Calendar.getInstance().getTimeInMillis());
        
        LottoMatriz lottoMatriz = new LottoMatriz();
        for(int i =0; i < 5; i++){
            LottoTicket lotto = new LottoTicket();
            lotto.setLotto(lottoCal);
            lottoMatriz.addLotto(lotto);
        }
        
        jLLottoMatriz.setText(lottoMatriz.toString());
        jLLottoMatriz.validate();
        
        // Delete from here
        /*
        System.out.println( lottoMatriz.toString());
        
        System.out.println(date.getTime() + " - " + Calendar.getInstance().getTimeInMillis()
        + " - " +lottoCal.getNuevaFechaSorteo());
            try {
                Thread.sleep(4000);
            } catch (InterruptedException ex) {
                Logger.getLogger(LottoPickerUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        System.out.println(date.getTime() + " - " + Calendar.getInstance().getTimeInMillis()
        + " - " +lottoCal.getNuevaFechaSorteo());
        */
        // To here
    }//GEN-LAST:event_jBGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LottoPickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LottoPickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LottoPickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LottoPickerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoPickerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGenerate;
    private com.toedter.calendar.JDateChooser jDCFechaSorteo;
    private javax.swing.JLabel jLLottoMatriz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPLottoMatriz;
    // End of variables declaration//GEN-END:variables
}
